---
# playbook to enable maintenance page for JIRA (used during maintenance windows)

- name: enable maintenace page
  hosts: all
  gather_facts: false
  vars_files:
    - ./vars/vault.yml
  tasks:
    - name: set ip_environment to be the same as instance_environment, if ip_environment is not set
      set_fact:
        ip_environment: "{{ instance_id[instance_environment] }}"
      when: ip_environment is not defined

    - name: associate an elastic IP with an instance and allow reassociation
      ec2_eip:
          device_id: "{{ instance_id[instance_environment] }}"
          ip: "{{ elastic_ip[ip_environment] }}"
          region: "{{ aws_region }}"
          allow_reassociation: yes
      delegate_to: localhost
